[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = '''
  source ~/.config/nvim/plugin_settings/coc.rc.vim
'''

[[plugins]]
repo='Shougo/denite.nvim'
on_cmd = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord']
on_func = ['denite#']
hook_add='''
  source ~/.config/nvim/plugin_settings/denite.rc.vim
'''

[[plugins]]
repo      = 'neoclide/denite-git'
on_source = ['denite.nvim']
depends   = ['vim-easygit']

[[plugins]]
repo = 'neoclide/vim-easygit'
hook_add='''
let g:easygit_enable_command = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add='''
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'sjl/badwolf'
hook_add = '''
syntax on
colorscheme badwolf
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends=['vim-airline-themes']
hook_add='''
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'badwolf'
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab
let g:airline#extensions#tabline#buffer_idx_mode = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    set diffopt+=vertical
    nnoremap <silent> ,s :<C-u>Gstatus<CR>
    nnoremap <silent> ,d :<C-u>Gdiff<CR>
    nnoremap <silent> ,b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

