[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add='''
let g:user_emmet_settings= {
\  'variables': {
\    'lang': "ja"
\  },
\  'javascript': {
\    'extends': 'jsx',
\  }
\}
autocmd FileType html,css,php,javascript,jsx EmmetInstall
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add  = ''' "{{{
map <C-m> :NERDTreeToggle<CR>
"}}} '''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo      = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_add  = ''' "{{{
  let g:fruzzy#usenative = 1
  let g:fruzzy#sortonempty = 0
"}}} '''
hook_post_update = 'call fruzzy#install()'

[[plugins]]
repo = 'glidenote/memolist.vim'
depends=['denite.nvim']
hook_add = '''
  let g:memolist_path = "~/onedrive/docs/"
  let g:memolist_denite =1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft=['markdown']
hook_post_update = './app/install.sh'

